Write-Host "Current time: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
Write-Host ""
Write-Host "Publishing AudioStudio..."
dotnet publish "E:\Atest1.0\AudioStudio\AudioStudio\AudioStudio.csproj" -c Release -r win-x64 --self-contained -o "E:\Atest1.0\AudioStudio\AudioStudio\publish" --force
Write-Host ""
Write-Host "Published EXE info:"
$exe = Get-Item "E:\Atest1.0\AudioStudio\AudioStudio\publish\AudioStudio.exe"
Write-Host "Path: $($exe.FullName)"
Write-Host "Size: $($exe.Length) bytes"
Write-Host "LastWriteTime: $($exe.LastWriteTime)"
Write-Host ""
Write-Host "Project ICO info:"
$ico = Get-Item "E:\Atest1.0\AudioStudio\AudioStudio\app.ico"
Write-Host "Path: $($ico.FullName)"
Write-Host "Size: $($ico.Length) bytes"
Write-Host "LastWriteTime: $($ico.LastWriteTime)"
