$results = @()
$results += "Current time: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
$results += ""
$results += "Publishing AudioStudio..."
$publishOutput = dotnet publish "E:\Atest1.0\AudioStudio\AudioStudio\AudioStudio.csproj" -c Release -r win-x64 --self-contained -o "E:\Atest1.0\AudioStudio\AudioStudio\publish" --force 2>&1
$results += $publishOutput
$results += ""
$results += "Published EXE info:"
$exe = Get-Item "E:\Atest1.0\AudioStudio\AudioStudio\publish\AudioStudio.exe"
$results += "Path: $($exe.FullName)"
$results += "Size: $($exe.Length) bytes"
$results += "LastWriteTime: $($exe.LastWriteTime)"
$results += ""
$results += "Project ICO info:"
$ico = Get-Item "E:\Atest1.0\AudioStudio\AudioStudio\app.ico"
$results += "Path: $($ico.FullName)"
$results += "Size: $($ico.Length) bytes"
$results += "LastWriteTime: $($ico.LastWriteTime)"
$results | Out-File -FilePath "E:\Atest1.0\AudioStudio\publish_result.txt" -Encoding UTF8
